name: Deploy via ftp
on: push
jobs:
  deploy:
    name: FTP Deploy Locaweb
    runs-on: ubuntu-latest
    steps:
    - uses: locaweb/ftp-deploy@1.0.0

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "dist"



            
