name: Deploy Locaweb FTP

on:
  push:
    branches:
      - main  # Altere para sua branch principal se necessário
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      # Se você precisar de build, descomente e ajuste conforme necessário
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      
      # - name: 🔨 Build Project
      #   run: |
      #     npm install
      #     npm run build
        
      - name: 📂 Deploy to Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}  
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "."        # Altere para "dist" se usar build
          remoteDir: "web"    # Use "web" para Windows ou "public_html" para Linux
          forceSSL: "false"   # Altere para "true" se precisar de SSL
