name: Deploy FTP
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: "ftp.solsticetech.com.br" 
        user: "solsticetech1"
        password: "Tigredesabre02@"
        localDir: "."
        remoteDir: "/home/solsticetech1/public_html"
        forceSSL: "false"
        options: "--verbose"  # Isso vai nos dar mais detalhes do erro
