name: Deploy FTP
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: 'ftp.solsticetech1.hospedagemdesites.ws'
        user: 'ftp.solsticetech.com.br'
        password: 'Tigredesabre02@'
        localDir: "."
        remoteDir: "/home/solsticetech1/public_html"
        forceSSL: "false"
        options: "--verbose"  # Isso vai nos dar mais detalhes do erro
